### ISSUE TITLE
Error executing action `create` on resource 'kibana_web[kibana]'

### ISSUE THREAD

**Issue by imewish** [lusis/chef-kibana#122]
Getting the following error when runs wth test kitchen.

```
* kibana_web[kibana] action create

           ================================================================================
           Error executing action `create` on resource 'kibana_web[kibana]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `[]' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/nginx/recipes/ohai_plugin.rb:27:in `from_file'
           /tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb:21:in `from_file'
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/web.rb:69:in `block (2 levels) in <class:KibanaWeb>'
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/web.rb:37:in `block in <class:KibanaWeb>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/kibana_lwrp/recipes/install.rb

            90: kibana_web 'kibana' do
            91:   type lazy { node['kibana']['webserver'] }
            92:   docroot docroot
            93:   es_server node['kibana']['es_server']
            94:   kibana_port node['kibana']['java_webserver_port']
            95:   template 'kibana-nginx_file.conf.erb'
            96:   not_if { node['kibana']['webserver'] == '' }
            97: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/kibana_lwrp/recipes/install.rb:90:in `from_file'

           kibana_web("kibana") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :kibana_web
             cookbook_name "kibana_lwrp"
             recipe_name "install"
             type #<ChefCompat::CopiedFromChef::Chef::DelayedEvaluator:0x000000068758b0@/tmp/kitchen/cache/cookbooks/kibana_lwrp/recipes/install.rb:91>
             docroot "/opt/kibana/current/kibana"
             es_server "127.0.0.1"
             kibana_port 5601
             template "kibana-nginx_file.conf.erb"
             template_cookbook "kibana_lwrp"
             server_name "kibana.localhost"
             server_aliases ["kibana"]
             listen_address "0.0.0.0"
             listen_port "80"
             es_port "9200"
             es_scheme "http://"
             version "4.2.1-linux-x64"
             not_if { #code block }
           end

           Platform:
           ---------
           x86_64-linux


```

**Comment by martinb3** [comment]
This looks like a duplicate of #117; we think this has something to do with a newer ohai that isn't populating the same node attributes as before. Specifically, it's the nginx cookbook that uses ohai attributes, that we depend on. The nginx cookbook is currently going through a re-write, so it's likely to be resolved in the near future.

**Comment by imewish** [comment]
How can i avoid it for now? @martinb3

**Comment by martinb3** [comment]
The other user reporting this found that pinning back ohai to a less brand-new version [as described here](https://github.com/lusis/chef-kibana/issues/121#issuecomment-234311735).

**Comment by imewish** [comment]
@martinb3  i have tried by adding the lower version of as dependency . Gives me version constrain error. :(

`>>>>>> Message: Failed to complete #converge action: [Unable to satisfy constraints on package ohai due to solution constraint`

**Comment by martinb3** [comment]
I'd be glad to debug if you had an example I could clone down. Let me know 👍

**Comment by imewish** [comment]
@martinb3  its just a wrapper cookbook that i created with this cookbook(lusis/chef-kibana) as a dependency. 

clone from here,
https://github.com/imewish/kibana

**Comment by martinb3** [comment]
It looks like newer nginx cookbooks ended up pinning back the ohai one, due to changes. Until nginx's cookbook is updated (it appears to be mid-stream on a rewrite), you'll need to also pin back ohai in `metadata.rb`:
```
depends 'ohai', '~> 1.1'
```

Changing that, I was able to get your example to converge. Hope it helps!

**Comment by eherot** [comment]
This issue should also be fixed by #125

**Comment by martinb3** [comment]
#125 has been merged, so I'm going to close this one. I'll reopen if we hear that there's still an issue. Thanks!
